version: '3.8'

services:
  gait_analysis:
#    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    env_file:
      - ./.env
    entrypoint: "python3.8 function.py"
